baseURL = "/"
languageCode = "en-us"
title = "My Photo Gallery"

# Use the gallery theme
theme = "gallery"

# Image processing settings
[imaging]
  anchor = "smart"
  quality = 85
  resampleFilter = "lanczos"

# Optional: Add social icons
[params.socialIcons]
  instagram = "https://www.instagram.com/yourusername/"
  github = "https://github.com/yourusername/"
  # Add other social networks as needed